
var github_html="";
github_html += "<!DOCTYPE html>";
github_html += "<html>";
github_html += "  <head lang=\"en\">";
github_html += "    <meta charset=\"UTF-8\">";
github_html += "";
github_html += "    <title>Trending - GitHub Explorer<\/title>";
github_html += "";
github_html += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
github_html += "    <meta name=\"description\" content=\"Advanced explorer of github.com. The main goal is to highlight the most interesting repositories and exclude others.\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/css\/normalize.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundicons\/3.0.0\/foundation-icons.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdn.jsdelivr.net\/foundation\/5.5.1\/css\/foundation.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/static\/styles.css\">";
github_html += "  <\/head>";
github_html += "";
github_html += "  <body>";
github_html += "    ";
github_html += "      ";
github_html += "    ";
github_html += "";
github_html += "    <nav class=\"top-bar\" data-topbar role=\"navigation\" style=\"margin-bottom: 2px\">";
github_html += "      <ul class=\"title-area\">";
github_html += "        <li class=\"name\">";
github_html += "          <h1><a href=\"\/\">Git Most Wanted<sup><small>alpha<\/small><\/sup><\/a><\/h1>";
github_html += "        <\/li>";
github_html += "        <li class=\"toggle-topbar menu-icon\"><a href=\"#\"><span><\/span><\/a><\/li>";
github_html += "      <\/ul>";
github_html += "";
github_html += "      <section class=\"top-bar-section\">";
github_html += "        <ul class=\"right\">";
github_html += "          <li><a href=\"https:\/\/github.com\/Letscodeit\/gitmostwanted.com\"";
github_html += "            target=\"_blank\">Fork it!<\/a><\/li>";
github_html += "          ";
github_html += "            <li><a href=\"\/oauth\/login\">Login via GitHub<\/a><\/li>";
github_html += "          ";
github_html += "        <\/ul>";
github_html += "      <\/section>";
github_html += "    <\/nav>";
github_html += "";
github_html += "    <div class=\"wrapper\">";
github_html += "      ";
github_html += "  <ul class=\"breadcrumbs\">";
github_html += "    ";
github_html += "      <li class=unavailable>";
github_html += "        <a href=\"\/\">Day<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "      <li >";
github_html += "        <a href=\"\/trending\/week\/\">Week<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "      <li >";
github_html += "        <a href=\"\/trending\/month\/\">Month<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "";
github_html += "    ";
github_html += "      <li class=\"unavailable\">";
github_html += "        <a href=\"\/oauth\/login?next=%2Funchecked%2F\">Attitude<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "  <\/ul>";
github_html += "";
github_html += "  <div class=\"row\" id=\"gh-entries\">";
github_html += "    <a href=\"#\" class=\"button tiny secondary\"><i class=\"fi-filter\"><\/i> Filter options<\/a>";
github_html += "  <form class=\"repository-filter hide clearfix\">";
github_html += "    <div class=\"small-8 medium-10 large-11 columns\">";
github_html += "      <select name=\"lang\">";
github_html += "        <option>All<\/option>";
github_html += "        ";
github_html += "          <option>Ruby<\/option>";
github_html += "        ";
github_html += "          <option>C++<\/option>";
github_html += "        ";
github_html += "          <option>Python<\/option>";
github_html += "        ";
github_html += "          <option>JavaScript<\/option>";
github_html += "        ";
github_html += "          <option>Shell<\/option>";
github_html += "        ";
github_html += "          <option>CoffeeScript<\/option>";
github_html += "        ";
github_html += "          <option>Objective-C<\/option>";
github_html += "        ";
github_html += "          <option>Erlang<\/option>";
github_html += "        ";
github_html += "          <option>Go<\/option>";
github_html += "        ";
github_html += "          <option>PHP<\/option>";
github_html += "        ";
github_html += "          <option>Rust<\/option>";
github_html += "        ";
github_html += "          <option>NSIS<\/option>";
github_html += "        ";
github_html += "          <option>OCaml<\/option>";
github_html += "        ";
github_html += "          <option>C#<\/option>";
github_html += "        ";
github_html += "          <option>Java<\/option>";
github_html += "        ";
github_html += "          <option>Assembly<\/option>";
github_html += "        ";
github_html += "          <option>TeX<\/option>";
github_html += "        ";
github_html += "          <option>Perl<\/option>";
github_html += "        ";
github_html += "          <option>CSS<\/option>";
github_html += "        ";
github_html += "          <option>C<\/option>";
github_html += "        ";
github_html += "          <option>HTML<\/option>";
github_html += "        ";
github_html += "          <option>Clojure<\/option>";
github_html += "        ";
github_html += "          <option>Haskell<\/option>";
github_html += "        ";
github_html += "          <option>Crystal<\/option>";
github_html += "        ";
github_html += "          <option>Emacs Lisp<\/option>";
github_html += "        ";
github_html += "          <option>Scala<\/option>";
github_html += "        ";
github_html += "          <option>VimL<\/option>";
github_html += "        ";
github_html += "          <option>Nimrod<\/option>";
github_html += "        ";
github_html += "          <option>ApacheConf<\/option>";
github_html += "        ";
github_html += "          <option>TypeScript<\/option>";
github_html += "        ";
github_html += "          <option>Haxe<\/option>";
github_html += "        ";
github_html += "          <option>Swift<\/option>";
github_html += "        ";
github_html += "          <option>Lua<\/option>";
github_html += "        ";
github_html += "          <option>PowerShell<\/option>";
github_html += "        ";
github_html += "          <option>Objective-C++<\/option>";
github_html += "        ";
github_html += "          <option>Arduino<\/option>";
github_html += "        ";
github_html += "          <option>Pascal<\/option>";
github_html += "        ";
github_html += "          <option>R<\/option>";
github_html += "        ";
github_html += "          <option>PLpgSQL<\/option>";
github_html += "        ";
github_html += "          <option>Kotlin<\/option>";
github_html += "        ";
github_html += "          <option>Dart<\/option>";
github_html += "        ";
github_html += "          <option>PureScript<\/option>";
github_html += "        ";
github_html += "          <option>Groff<\/option>";
github_html += "        ";
github_html += "          <option>Makefile<\/option>";
github_html += "        ";
github_html += "          <option>Cuda<\/option>";
github_html += "        ";
github_html += "          <option>AutoHotkey<\/option>";
github_html += "        ";
github_html += "          <option>Elm<\/option>";
github_html += "        ";
github_html += "          <option>PostScript<\/option>";
github_html += "        ";
github_html += "          <option>Elixir<\/option>";
github_html += "        ";
github_html += "          <option>ANTLR<\/option>";
github_html += "        ";
github_html += "          <option>Common Lisp<\/option>";
github_html += "        ";
github_html += "          <option>Visual Basic<\/option>";
github_html += "        ";
github_html += "          <option>Batchfile<\/option>";
github_html += "        ";
github_html += "          <option>AppleScript<\/option>";
github_html += "        ";
github_html += "      <\/select>";
github_html += "    <\/div>";
github_html += "    <div class=\"small-4 medium-2 large-1 columns\">";
github_html += "      <a href=\"#\" class=\"button tiny\">Reset<\/a>";
github_html += "    <\/div>";
github_html += "";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <div class=\"row\">";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"statusPromising\" type=\"radio\" value=\"promising\" name=\"status\"";
github_html += "              checked>";
github_html += "            <label for=\"statusPromising\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label success has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only Promising repositories\">P<\/span>";
github_html += "        <\/div>";
github_html += "";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"statusHopeless\" type=\"radio\" value=\"hopeless\" name=\"status\"";
github_html += "              >";
github_html += "            <label for=\"statusHopeless\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label warning has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only Hopeless repositories\">H<\/span>";
github_html += "        <\/div>";
github_html += "";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"maturityFlag\" type=\"checkbox\" name=\"mature\" value=\"1\"";
github_html += "              checked>";
github_html += "            <label for=\"maturityFlag\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label secondary has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only mature enough (older than 3 months) repositories\">M<\/span>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-3 columns\">&nbsp;<\/div>";
github_html += "      <\/div>";
github_html += "    <\/div>";
github_html += "  <\/form>";
github_html += "";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <ul class=\"small-block-grid-1 medium-block-grid-2 large-block-grid-3\">";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/01org\/acat\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/01org\/acat\" target=\"_blank\">01org\/acat<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">C#<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Assistive Context-Aware Toolkit<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +240 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/getlantern\/lantern\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/getlantern\/lantern\" target=\"_blank\">getlantern\/lantern<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">Go<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"https:\/\/getlantern.org\" target=\"_blank\">https:\/\/getlantern.org<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Open Internet for everyone. Lantern is a free desktop application that delivers fast, reliable and secure access to the open Internet.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +224 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/twbs\/bootstrap\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/twbs\/bootstrap\" target=\"_blank\">twbs\/bootstrap<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
// github_html += "          <sup class=\"success var github_html="";
github_html += "<!DOCTYPE html>";
github_html += "<html>";
github_html += "  <head lang=\"en\">";
github_html += "    <meta charset=\"UTF-8\">";
github_html += "";
github_html += "    <title>Trending - GitHub Explorer<\/title>";
github_html += "";
github_html += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
github_html += "    <meta name=\"description\" content=\"Advanced explorer of github.com. The main goal is to highlight the most interesting repositories and exclude others.\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/css\/normalize.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundicons\/3.0.0\/foundation-icons.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/\/cdn.jsdelivr.net\/foundation\/5.5.1\/css\/foundation.min.css\">";
github_html += "    <link rel=\"stylesheet\" href=\"\/static\/styles.css\">";
github_html += "  <\/head>";
github_html += "";
github_html += "  <body>";
github_html += "    ";
github_html += "      ";
github_html += "    ";
github_html += "";
github_html += "    <nav class=\"top-bar\" data-topbar role=\"navigation\" style=\"margin-bottom: 2px\">";
github_html += "      <ul class=\"title-area\">";
github_html += "        <li class=\"name\">";
github_html += "          <h1><a href=\"\/\">Git Most Wanted<sup><small>alpha<\/small><\/sup><\/a><\/h1>";
github_html += "        <\/li>";
github_html += "        <li class=\"toggle-topbar menu-icon\"><a href=\"#\"><span><\/span><\/a><\/li>";
github_html += "      <\/ul>";
github_html += "";
github_html += "      <section class=\"top-bar-section\">";
github_html += "        <ul class=\"right\">";
github_html += "          <li><a href=\"https:\/\/github.com\/Letscodeit\/gitmostwanted.com\"";
github_html += "            target=\"_blank\">Fork it!<\/a><\/li>";
github_html += "          ";
github_html += "            <li><a href=\"\/oauth\/login\">Login via GitHub<\/a><\/li>";
github_html += "          ";
github_html += "        <\/ul>";
github_html += "      <\/section>";
github_html += "    <\/nav>";
github_html += "";
github_html += "    <div class=\"wrapper\">";
github_html += "      ";
github_html += "  <ul class=\"breadcrumbs\">";
github_html += "    ";
github_html += "      <li class=unavailable>";
github_html += "        <a href=\"\/\">Day<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "      <li >";
github_html += "        <a href=\"\/trending\/week\/\">Week<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "      <li >";
github_html += "        <a href=\"\/trending\/month\/\">Month<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "";
github_html += "    ";
github_html += "      <li class=\"unavailable\">";
github_html += "        <a href=\"\/oauth\/login?next=%2Funchecked%2F\">Attitude<\/a>";
github_html += "      <\/li>";
github_html += "    ";
github_html += "  <\/ul>";
github_html += "";
github_html += "  <div class=\"row\" id=\"gh-entries\">";
github_html += "    <a href=\"#\" class=\"button tiny secondary\"><i class=\"fi-filter\"><\/i> Filter options<\/a>";
github_html += "  <form class=\"repository-filter hide clearfix\">";
github_html += "    <div class=\"small-8 medium-10 large-11 columns\">";
github_html += "      <select name=\"lang\">";
github_html += "        <option>All<\/option>";
github_html += "        ";
github_html += "          <option>Ruby<\/option>";
github_html += "        ";
github_html += "          <option>C++<\/option>";
github_html += "        ";
github_html += "          <option>Python<\/option>";
github_html += "        ";
github_html += "          <option>JavaScript<\/option>";
github_html += "        ";
github_html += "          <option>Shell<\/option>";
github_html += "        ";
github_html += "          <option>CoffeeScript<\/option>";
github_html += "        ";
github_html += "          <option>Objective-C<\/option>";
github_html += "        ";
github_html += "          <option>Erlang<\/option>";
github_html += "        ";
github_html += "          <option>Go<\/option>";
github_html += "        ";
github_html += "          <option>PHP<\/option>";
github_html += "        ";
github_html += "          <option>Rust<\/option>";
github_html += "        ";
github_html += "          <option>NSIS<\/option>";
github_html += "        ";
github_html += "          <option>OCaml<\/option>";
github_html += "        ";
github_html += "          <option>C#<\/option>";
github_html += "        ";
github_html += "          <option>Java<\/option>";
github_html += "        ";
github_html += "          <option>Assembly<\/option>";
github_html += "        ";
github_html += "          <option>TeX<\/option>";
github_html += "        ";
github_html += "          <option>Perl<\/option>";
github_html += "        ";
github_html += "          <option>CSS<\/option>";
github_html += "        ";
github_html += "          <option>C<\/option>";
github_html += "        ";
github_html += "          <option>HTML<\/option>";
github_html += "        ";
github_html += "          <option>Clojure<\/option>";
github_html += "        ";
github_html += "          <option>Haskell<\/option>";
github_html += "        ";
github_html += "          <option>Crystal<\/option>";
github_html += "        ";
github_html += "          <option>Emacs Lisp<\/option>";
github_html += "        ";
github_html += "          <option>Scala<\/option>";
github_html += "        ";
github_html += "          <option>VimL<\/option>";
github_html += "        ";
github_html += "          <option>Nimrod<\/option>";
github_html += "        ";
github_html += "          <option>ApacheConf<\/option>";
github_html += "        ";
github_html += "          <option>TypeScript<\/option>";
github_html += "        ";
github_html += "          <option>Haxe<\/option>";
github_html += "        ";
github_html += "          <option>Swift<\/option>";
github_html += "        ";
github_html += "          <option>Lua<\/option>";
github_html += "        ";
github_html += "          <option>PowerShell<\/option>";
github_html += "        ";
github_html += "          <option>Objective-C++<\/option>";
github_html += "        ";
github_html += "          <option>Arduino<\/option>";
github_html += "        ";
github_html += "          <option>Pascal<\/option>";
github_html += "        ";
github_html += "          <option>R<\/option>";
github_html += "        ";
github_html += "          <option>PLpgSQL<\/option>";
github_html += "        ";
github_html += "          <option>Kotlin<\/option>";
github_html += "        ";
github_html += "          <option>Dart<\/option>";
github_html += "        ";
github_html += "          <option>PureScript<\/option>";
github_html += "        ";
github_html += "          <option>Groff<\/option>";
github_html += "        ";
github_html += "          <option>Makefile<\/option>";
github_html += "        ";
github_html += "          <option>Cuda<\/option>";
github_html += "        ";
github_html += "          <option>AutoHotkey<\/option>";
github_html += "        ";
github_html += "          <option>Elm<\/option>";
github_html += "        ";
github_html += "          <option>PostScript<\/option>";
github_html += "        ";
github_html += "          <option>Elixir<\/option>";
github_html += "        ";
github_html += "          <option>ANTLR<\/option>";
github_html += "        ";
github_html += "          <option>Common Lisp<\/option>";
github_html += "        ";
github_html += "          <option>Visual Basic<\/option>";
github_html += "        ";
github_html += "          <option>Batchfile<\/option>";
github_html += "        ";
github_html += "          <option>AppleScript<\/option>";
github_html += "        ";
github_html += "      <\/select>";
github_html += "    <\/div>";
github_html += "    <div class=\"small-4 medium-2 large-1 columns\">";
github_html += "      <a href=\"#\" class=\"button tiny\">Reset<\/a>";
github_html += "    <\/div>";
github_html += "";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <div class=\"row\">";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"statusPromising\" type=\"radio\" value=\"promising\" name=\"status\"";
github_html += "              checked>";
github_html += "            <label for=\"statusPromising\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label success has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only Promising repositories\">P<\/span>";
github_html += "        <\/div>";
github_html += "";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"statusHopeless\" type=\"radio\" value=\"hopeless\" name=\"status\"";
github_html += "              >";
github_html += "            <label for=\"statusHopeless\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label warning has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only Hopeless repositories\">H<\/span>";
github_html += "        <\/div>";
github_html += "";
github_html += "        <div class=\"small-2 medium-2 text-right columns\">";
github_html += "          <div class=\"switch small radius\">";
github_html += "            <input id=\"maturityFlag\" type=\"checkbox\" name=\"mature\" value=\"1\"";
github_html += "              checked>";
github_html += "            <label for=\"maturityFlag\"><\/label>";
github_html += "          <\/div>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-1 columns\">";
github_html += "          <span class=\"label secondary has-tip\" data-tooltip aria-haspopup=\"true\"";
github_html += "            title=\"Show only mature enough (older than 3 months) repositories\">M<\/span>";
github_html += "        <\/div>";
github_html += "        <div class=\"small-3 columns\">&nbsp;<\/div>";
github_html += "      <\/div>";
github_html += "    <\/div>";
github_html += "  <\/form>";
github_html += "";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <ul class=\"small-block-grid-1 medium-block-grid-2 large-block-grid-3\">";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/01org\/acat\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/01org\/acat\" target=\"_blank\">01org\/acat<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">C#<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Assistive Context-Aware Toolkit<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +240 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/getlantern\/lantern\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/getlantern\/lantern\" target=\"_blank\">getlantern\/lantern<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">Go<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"https:\/\/getlantern.org\" target=\"_blank\">https:\/\/getlantern.org<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Open Internet for everyone. Lantern is a free desktop application that delivers fast, reliable and secure access to the open Internet.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +224 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/twbs\/bootstrap\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/twbs\/bootstrap\" target=\"_blank\">twbs\/bootstrap<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">CSS<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/getbootstrap.com\" target=\"_blank\">http:\/\/getbootstrap.com<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +221 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/FreeCodeCamp\/FreeCodeCamp\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/FreeCodeCamp\/FreeCodeCamp\" target=\"_blank\">FreeCodeCamp\/FreeCodeCamp<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">HTML<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The http:\/\/FreeCodeCamp.com open-source codebase and curriculum. Practice coding by helping nonprofits.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +195 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/dypsilon\/frontend-dev-bookmarks\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/dypsilon\/frontend-dev-bookmarks\" target=\"_blank\">dypsilon\/frontend-dev-bookmarks<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>A huge list of frontend development resources I collected over time. Sorted from general knowledge at the top to concrete problems at the bottom.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +159 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/postcss\/postcss\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/postcss\/postcss\" target=\"_blank\">postcss\/postcss<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">JavaScript<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"https:\/\/twitter.com\/postcss\" target=\"_blank\">https:\/\/twitter.com\/postcss<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Transforming styles with JS plugins<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +114 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/jnv\/lists\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/jnv\/lists\" target=\"_blank\">jnv\/lists<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The definitive list of lists (of lists) curated on GitHub<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +94 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/google\/material-design-lite\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/google\/material-design-lite\" target=\"_blank\">google\/material-design-lite<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">CSS<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/getmdl.io\" target=\"_blank\">http:\/\/getmdl.io<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Material Design Lite Components in HTML\/CSS\/JS<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +79 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/sindresorhus\/awesome\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/sindresorhus\/awesome\" target=\"_blank\">sindresorhus\/awesome<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>A curated list of awesome lists<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +72 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/atom\/electron\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/atom\/electron\" target=\"_blank\">atom\/electron<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">C++<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/electron.atom.io\" target=\"_blank\">http:\/\/electron.atom.io<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Build cross platform desktop apps with web technologies<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +68 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "      <\/ul>";
github_html += "    <\/div>";
github_html += "  <\/div>";
github_html += "";
github_html += "      <div class=\"footer-push\"><\/div>";
github_html += "    <\/div>";
github_html += "";
github_html += "    <footer>";
github_html += "  <div class=\"row\">";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <iframe";
github_html += "        src=\"https:\/\/ghbtns.com\/github-btn.html?user=kkamkou&repo=gitmostwanted.com&type=fork&size=large&v=2\"";
github_html += "        frameborder=\"0\" scrolling=\"0\" width=\"80px\" height=\"30px\" class=\"right\"><\/iframe>";
github_html += "";
github_html += "      <ul class=\"inline-list left\">";
github_html += "        <li>";
github_html += "          <a href=\"https:\/\/github.com\/kkamkou\/gitmostwanted.com\/wiki\" target=\"_blank\">Wiki<\/a>";
github_html += "        <\/li>";
github_html += "      <\/ul>";
github_html += "    <\/div>";
github_html += "  <\/div>";
github_html += "<\/footer>";
github_html += "  <\/body>";
github_html += "";
github_html += "  <!-- ga -->";
github_html += "  <script type=\"text\/javascript\">";
github_html += "    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){";
github_html += "        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),";
github_html += "            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)";
github_html += "    })(window,document,'script','\/\/www.google-analytics.com\/analytics.js','ga');";
github_html += "    ga('create', 'UA-62018427-1', 'auto');";
github_html += "    ga('send', 'pageview');";
github_html += "  <\/script>";
github_html += "  <!-- \/ga -->";
github_html += "";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/vendor\/jquery.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/vendor\/modernizr.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/foundation.min.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/static\/common.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\">";
github_html += "    $(document).foundation();";
github_html += "  <\/script>";
github_html += "";
github_html += "  ";
github_html += "<\/html>";
github_html += "";
label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">CSS<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/getbootstrap.com\" target=\"_blank\">http:\/\/getbootstrap.com<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +221 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/FreeCodeCamp\/FreeCodeCamp\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/FreeCodeCamp\/FreeCodeCamp\" target=\"_blank\">FreeCodeCamp\/FreeCodeCamp<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">HTML<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The http:\/\/FreeCodeCamp.com open-source codebase and curriculum. Practice coding by helping nonprofits.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +195 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/dypsilon\/frontend-dev-bookmarks\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/dypsilon\/frontend-dev-bookmarks\" target=\"_blank\">dypsilon\/frontend-dev-bookmarks<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>A huge list of frontend development resources I collected over time. Sorted from general knowledge at the top to concrete problems at the bottom.<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +159 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/postcss\/postcss\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/postcss\/postcss\" target=\"_blank\">postcss\/postcss<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">JavaScript<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"https:\/\/twitter.com\/postcss\" target=\"_blank\">https:\/\/twitter.com\/postcss<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Transforming styles with JS plugins<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +114 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/jnv\/lists\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/jnv\/lists\" target=\"_blank\">jnv\/lists<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>The definitive list of lists (of lists) curated on GitHub<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +94 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/google\/material-design-lite\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/google\/material-design-lite\" target=\"_blank\">google\/material-design-lite<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">CSS<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/getmdl.io\" target=\"_blank\">http:\/\/getmdl.io<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Material Design Lite Components in HTML\/CSS\/JS<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +79 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/sindresorhus\/awesome\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/sindresorhus\/awesome\" target=\"_blank\">sindresorhus\/awesome<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>A curated list of awesome lists<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +72 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "          <li data-url=\"https:\/\/github.com\/atom\/electron\">";
github_html += "    <div>";
github_html += "      <h4>";
github_html += "        <a href=\"https:\/\/github.com\/atom\/electron\" target=\"_blank\">atom\/electron<\/a>";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"secondary label\" title=\"Mature enough (Older than 3 months)\">m<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <sup class=\"success label\"";
github_html += "            title=\"Promising\">p<\/sup>";
github_html += "        ";
github_html += "";
github_html += "        ";
github_html += "          <small class=\"right\">C++<\/small>";
github_html += "        ";
github_html += "      <\/h4>";
github_html += "";
github_html += "      ";
github_html += "        <a href=\"http:\/\/electron.atom.io\" target=\"_blank\">http:\/\/electron.atom.io<\/a>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "        <p>Build cross platform desktop apps with web technologies<\/p>";
github_html += "      ";
github_html += "";
github_html += "      ";
github_html += "            <div class=\"right\">";
github_html += "              <span class=\"label secondary\">";
github_html += "                +68 <i class=\"fi-star\"><\/i>";
github_html += "              <\/span>";
github_html += "            <\/div>";
github_html += "";
github_html += "            ";
github_html += "          ";
github_html += "    <\/div>";
github_html += "  <\/li>";
github_html += "        ";
github_html += "      <\/ul>";
github_html += "    <\/div>";
github_html += "  <\/div>";
github_html += "";
github_html += "      <div class=\"footer-push\"><\/div>";
github_html += "    <\/div>";
github_html += "";
github_html += "    <footer>";
github_html += "  <div class=\"row\">";
github_html += "    <div class=\"small-12 columns\">";
github_html += "      <iframe";
github_html += "        src=\"https:\/\/ghbtns.com\/github-btn.html?user=kkamkou&repo=gitmostwanted.com&type=fork&size=large&v=2\"";
github_html += "        frameborder=\"0\" scrolling=\"0\" width=\"80px\" height=\"30px\" class=\"right\"><\/iframe>";
github_html += "";
github_html += "      <ul class=\"inline-list left\">";
github_html += "        <li>";
github_html += "          <a href=\"https:\/\/github.com\/kkamkou\/gitmostwanted.com\/wiki\" target=\"_blank\">Wiki<\/a>";
github_html += "        <\/li>";
github_html += "      <\/ul>";
github_html += "    <\/div>";
github_html += "  <\/div>";
github_html += "<\/footer>";
github_html += "  <\/body>";
github_html += "";
github_html += "  <!-- ga -->";
github_html += "  <script type=\"text\/javascript\">";
github_html += "    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){";
github_html += "        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),";
github_html += "            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)";
github_html += "    })(window,document,'script','\/\/www.google-analytics.com\/analytics.js','ga');";
github_html += "    ga('create', 'UA-62018427-1', 'auto');";
github_html += "    ga('send', 'pageview');";
github_html += "  <\/script>";
github_html += "  <!-- \/ga -->";
github_html += "";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/vendor\/jquery.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/vendor\/modernizr.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/\/cdnjs.cloudflare.com\/ajax\/libs\/foundation\/5.5.1\/js\/foundation.min.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\" src=\"\/static\/common.js\"><\/script>";
github_html += "  <script type=\"text\/javascript\">";
github_html += "    $(document).foundation();";
github_html += "  <\/script>";
github_html += "";
github_html += "  ";
github_html += "<\/html>";
github_html += "";




var el = document.createElement( 'html' );

el.innerHTML = github_html;

console.log(el.getElementsByTagName( 'a' ));



